apiVersion: v1
kind: Namespace
metadata:
  name: felipe
---
apiVersion: v1
kind: PersistentVolumClaim
metadata:
  name: felipe-volume
  namespace: felipe
spec:
  storageClassName: longhorn
  acessModes: 
  - ReadWriteOnce
  resources: 
    requests: 
      storage: 1Gi
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: felipe-ingress
  namespace: felipe
spec:
  ingressClassName: nginx
  rules:
  - host: felipe.fevereiro.jac.bsb.br
    http:
      paths:
      - backend:
          service:
            name: felipe-servico
            port:
              number: 80
        path: /
        pathType: Prefix
---
apiVersion: v1
kind: Service
metadata:
  name: felipe-servico
  namespace: felipe
spec:
  ports:
  - port: 80
    targetPort: 3000
    
  selector:
    app: felipe
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: felipe-deploy
  namespace: felipe
spec:
  replicas: 1
  selector:
    matchLabels:
      app: felipe
  template:
    metadata:
      labels:
        app: felipe
    spec:
      volumes: 
      - name: felipe-volume
      persistentVolumeClaim:
      claimName: felipe-volume
      containers:
      - image: rishikoy/theiaide-full:1.0.0-SNAPSHOT
        name: felipe-theiaide
        ports:
        - containerPort: 3000
        volumeMounts: 
        - mountPath: /home/project
          name: felipe-volume

